Fix loading with playlist.
In osmplayer.teaser.js:
  line 52:    var image = osmplayer.getImage(node.mediafiles, 'thumbnail');

no callback is given to osmplayer.getImage,  so the player crash with:
  Uncaught TypeError: undefined is not a function

So if no callback defined, osmplayer.getImage creates one.